- name: Generate GitHub Stats SVG
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=dark
          path: profile/stats.svg
          # 👇 在这里直接调用你以前存好的 Token
          token: ${{ secrets.SUMMARY_CARD_TOKEN }} 
          
      - name: Generate Top Languages SVG
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&show_icons=true&theme=dark&layout=compact
          path: profile/top-langs.svg
          # 👇 同样在这里复用
          token: ${{ secrets.SUMMARY_CARD_TOKEN }}
